# Generated by Django 5.2.15 on 2026-06-28 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuseumProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("curator", "Curador"),
                            ("technician", "Técnico"),
                            ("visitor", "Visitante"),
                        ],
                        default="visitor",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="museum_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("available", "Disponível"),
                            ("reserved", "Reservada"),
                            ("checked_out", "Retirada"),
                            ("quarantine", "Quarentena"),
                            ("retired", "Aposentada"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("available", "Disponível"),
                            ("reserved", "Reservada"),
                            ("checked_out", "Retirada"),
                            ("quarantine", "Quarentena"),
                            ("retired", "Aposentada"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor", models.CharField(blank=True, max_length=120)),
                ("reason", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_changes",
                        to="scents.capsule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
